language: node_js
node_js:
  - "stable"

branches:
  only:
    - dep-inclusions

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g yarn

script:
  # - yarn lint
  - yarn build
  - mv build/index.html build/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: build
  on:
    branch: master
